services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # Add tag for interface
    _instanceof:
        ZyosInstallBundle\Interfaces\ValidatorInterface:
            lazy: true
            public: true
            tags: ['zyos_install.validators']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    ZyosInstallBundle\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
        public: false

    # handler collection for validations
    ZyosInstallBundle\Handlers\ValidationCollections:
        # inject all services tagged with app.handler as first argument
        # and use the value of the 'key' tag attribute to index the services
        arguments: [!tagged { tag: 'zyos_install.validators', default_index_method: 'getName' }]